#!/usr/bin/env Rscript

src = "src"
dest = "docs"
f = basename(commandArgs(TRUE)[1L])
macros = list(
  list(pattern = "\\\\man\\[([[:alnum:]]+)\\]", replacement = "[\\1](../../../man/\\1.html)"),
  list(pattern = "\\\\man2\\[([[:alnum:]()]+)\\]\\[([[:alnum:]]+)\\]", replacement = "[\\1](../../../man/\\2.html)")
)

library(methods)
library(BBmisc, quietly = TRUE)
library(knitr, quietly = TRUE)
library(stringr, quietly = TRUE)
library(digest, quietly = TRUE)
library(mlr, quietly = TRUE)

options(warn = 2L)
opts_knit$set(upload.fun = image_uri)

exit = function(status, msg, ...) {
  if (!missing(msg))
    cat(sprintf(msg, ...), "\n\n", sep = "")
  quit(save = "no", status = status)
}

objToSeed = function(x, algo="crc32") {
 hash = digest(x, algo = algo)
 strtoi(sprintf("0x%s", substr(hash, 1L, 7L)))
}

if (!isDirectory("docs"))
  dir.create("docs")

lines = readLines(file.path(src, f))
for (macro in macros)
  lines = str_replace_all(lines, macro$pattern, macro$replacement)
cache.path = paste0(file.path("cache", f), .Platform$file.sep)

opts_chunk$set(cache = TRUE, cache.path = cache.path)
set.seed(objToSeed(f))
ok = try(knit(text = lines, output = file.path(dest, str_replace(f, "\\.Rmd$", "\\.md")), quiet = TRUE))
if (inherits(ok, "try-error"))
  exit(1L, "Error knitting file '%s':\n%s", f, as.character(ok))
exit(0L)

# vim: set ft=r:
