context("mbo initial design")

test_that("mbo works correctly with and without initial design", {
  f = makeMBOFunction(function(x) sum(x^2))
  
  ps = makeParamSet(
    makeNumericParam("x1", lower=-2, upper=1), 
    makeNumericParam("x2", lower=-1, upper=2) 
  )
	
  learner = makeLearner("regr.km", nugget.estim=TRUE)
  ctrl = makeMBOControl(iters=5, infill.opt.random.points=10)
	
	# PROVIDE INITIAL DESIGN WITHOUT TRAFO
  des = generateDesign(10, par.set=ps)
	
  or = mbo(f, ps, des, learner, ctrl)
  expect_true(!is.na(or$y),
		"mbo should work fine on initial design generated by 'generateDesign'")
	
	ps <- makeParamSet(
	  makeNumericParam("x1", lower=-2, upper=1),
	  makeNumericParam("x2", lower=-1, upper=2, trafo=function(x) x/2)
	)
	
	# PROVIDE INITIAL DESIGN WITH TRAFO
	des = generateDesign(10, ps, trafo=TRUE)
	expect_error(mbo(f, ps, des, learner, ctrl))
	
	# PROVIDE INITIAL DESIGN WITH UNMATCHING COLUMN NAMES	
	des = data.frame(x1 = c(-0.49, 0.24, -1.47), z = c(-0.70, 1.29, 0.73))
	expect_error(mbo(f, ps, des, learnrer, ctrl))
})
