---
title: "mlr-tutorial"
author: "Julia Schiffner, Bernd Bischl, Michel Lang, Jakob Richter, Zachary M. Jones, Philipp Probst, Florian Pfisterer, Mason Gallo, Dominik Kirchhoff, Tobias Kühn, Janek Thomas, Kira Engelhardt, Teodora Pandeva, Gunnar König, Lars Kotthoff"
output: 
  bookdown::pdf_document2:
    number_sections: true
    toc_depth: 2
biblio-style: apalike
link-citations: yes
---

# Basics

```{r child = '../task.Rmd'}
```

```{r child = '../learners.Rmd'}
```

```{r child = '../predict.Rmd'}
```

```{r child = '../performance.Rmd'}
```

```{r child = '../resampling.Rmd'}
```

```{r child = '../tune.Rmd'}
```

```{r child = '../benchmark_experiments.Rmd'}
```

```{r child = '../parallelization.Rmd'}
```

```{r child = '../visualization.Rmd'}
```

# Advanced

```{r child = '../configuring.Rmd'}
```

```{r child = '../wrapper.Rmd'}
```

```{r child = '../preproc.Rmd'}
```

```{r child = '../configuring.Rmd'}
```

```{r child = '../impute.Rmd'}
```

```{r child = '../bagging.Rmd'}
```

```{r child = '../advanced_tune.Rmd'}
```

```{r child = '../feature_selection.Rmd'}
```

```{r child = '../nested_resampling.Rmd'}
```

```{r child = '../cost_sensitive_classif.Rmd'}
```

```{r child = '../imbalanced_classification_problems.Rmd'}
```

```{r child = '../roc_analysis.Rmd'}
```

```{r child = '../multilabel.Rmd'}
```

```{r child = '../learning_curve_analysis.Rmd'}
```

```{r child = '../partial_dependence.Rmd'}
```

```{r child = '../classifier_calibration.Rmd'}
```

```{r child = '../hyperparameter_tuning_effects.Rmd'}
```

```{r child = '../out_of_bag_predictions.Rmd'}
```

```{r child = '../handling_of_spatial_data.Rmd'}
```

```{r child = '../configuring.Rmd'}
```

# Extending

```{r child = '../custom_learners.Rmd'}
```

```{r child = '../custom_measures.Rmd'}
```

```{r child = '../create_imputation.Rmd'}
```

```{r child = '../create_filter.Rmd'}
```

# Appendix

```{r child = '../example_tasks.Rmd'}
```

```{r child = '../integrated_learners.Rmd'}
```

```{r child = '../implemented_measures.Rmd'}
```

```{r child = '../filter_methods.Rmd'}
```
