# mlr Tutorial
This web page provides an in-depth introduction on how to
use the [%mlr] framework for machine learning experiments and
optimization in **R**.

We focus on the comprehension of the basic functions and applications.
More detailed technical information can be found in the [manual pages](http://berndbischl.github.io/mlr/man/) which
are regularly updated and reflect the documentation of the [current package version on CRAN](http://cran.r-project.org/web/packages/mlr/index.html).

An offline version of this of this tutorial is available for download [here](http://berndbischl.github.io/mlr/tutorial/mlr_tutorial.zip).

The tutorial explains the basic analysis of a data set step by step:

* What is your data and the aim of your analysis? [Tasks](task.md)
* How do you select learning algorithms and set them up? [Learners](learner.md), [Train](train.md)
* How to predict given new data? [Predict](predict.md)
* How to evaluate models and their predictions? [Performance](performance.md), [Resampling](resample.md)
* How to tune models? [Tuning](tune.md)
* How to select important features? [Feature Selection](feature_selection.md)
* How to conduct a comparison study? [Benchmark Experiments](benchmark_experiments.md)

We present various simple examples from classification, regression, cluster and survival
analysis during this tutorial to illustrate the main features of the
package.

Enjoy reading!


## Quick start
A simple stratified cross-validation of the *linear discriminant analysis* with [%mlr].
```{r}
library(mlr)
data(iris)

## Define the task:
task = makeClassifTask(id = "tutorial", data = iris, target = "Species")

## Define the learner:
lrn = makeLearner("classif.lda")

## Define the resampling strategy:
rdesc = makeResampleDesc(method = "CV", stratify = TRUE)

## Do the resampling:
r = resample(learner = lrn, task = task, resampling = rdesc, show.info = FALSE)

## Get the mean misclassification error:
r$aggr
```
