context("FDA_FeatExtraction")

test_that("FDA_FeatExtraction", {
  gp = getTaskData(gunpoint.task, target.extra = TRUE)
  d = extractFDAFeatures(data = gp$data, target = getTaskTargetNames(gunpoint.task), method = "fourier", args = list())
  gp = getTaskData(gunpoint.task, target.extra = TRUE)
  d = extractFDAFeatures(data = gp$data, target = getTaskTargetNames(gunpoint.task), method = "wavelets", args = list( filter = "d4", boundary = "reflection"))
  expect_true(dim(d$feat)[1] == dim(gp$data)[1])
  d = extractFDAFeatures(data = gp$data, target = getTaskTargetNames(gunpoint.task), method = "multiRes", args = list())
  expect_true(dim(d$feat)[1] == dim(gp$data)[1])
  d = extractFDAFeatures(data = gp$data, target = getTaskTargetNames(gunpoint.task), method = "bsignal", args = list())
  expect_true(dim(d$feat)[1] == dim(gp$data)[1])
  d = extractFDAFeatures(data = gp$data, target = getTaskTargetNames(gunpoint.task), method = "fpca", args = list())
  expect_true(dim(d$feat)[1] == dim(gp$data)[1])
})


test_that("FDA_MultiFeatExtraction", {
  fuel = getTaskData(fuelsubset.task, target.extra = TRUE)
  tdesc = getTaskDesc(fuelsubset.task)
  # d = extractMultiFDAFeatures(data = fuel$data, target = getTaskTargetNames(fuelsubset.task), fd.features = tdesc$fd.features , method = "wavelets", args = list( filter = "d4", boundary = "reflection"))
  # expect_true(dim(d)[1] == dim(fuel$data)[1])
  # d = extractMultiFDAFeatures(data = fuel$data, target = getTaskTargetNames(fuelsubset.task), fd.features = tdesc$fd.features , method = "fourier", args = list())
  # expect_true(dim(d)[1] == dim(fuel$data)[1])
  # d = extractMultiFDAFeatures(data = fuel$data, target = getTaskTargetNames(fuelsubset.task), fd.features = tdesc$fd.features , method = "multiRes", args = list())
  # expect_true(dim(d)[1] == dim(fuel$data)[1])
  # d = extractMultiFDAFeatures(data = fuel$data, target = getTaskTargetNames(fuelsubset.task), fd.features = tdesc$fd.features , method = "bsignal", args = list())
  # expect_true(dim(d)[1] == dim(fuel$data)[1])
  # d = extractMultiFDAFeatures(data = fuel$data, target = getTaskTargetNames(fuelsubset.task), fd.features = tdesc$fd.features , method = "fpca", args = list())
  # expect_true(dim(d)[1] == dim(fuel$data)[1])
})
