context("FDA_ConvertTask")
test_that("FDA_ConvertTask", {
  fuel = getTaskData(fuelSubset.task, target.extra = TRUE)
  tdesc = getTaskDescription(fuelSubset.task)
  task = trafoFDATaskToRegrTask(task = fuelSubset.task, method = "wavelets", pars = list( filter = "d4", boundary = "reflection"))
  expect_true(nrow(getTaskData(task))== dim(fuel$data)[1])
  task = trafoFDATaskToRegrTask(task = fuelSubset.task, method = "fourier", pars = list())
  expect_true(nrow(getTaskData(task)) == dim(fuel$data)[1])
  task = trafoFDATaskToRegrTask(task = fuelSubset.task, method = "multiRes", pars = list())
  expect_true(nrow(getTaskData(task)) == dim(fuel$data)[1])
  task = trafoFDATaskToRegrTask(task = fuelSubset.task, method = "bsignal", pars = list())
  expect_true(nrow(getTaskData(task)) == dim(fuel$data)[1])
  task = trafoFDATaskToRegrTask(task = fuelSubset.task, method = "fpca", pars = list())
  expect_true(nrow(getTaskData(task)) == dim(fuel$data)[1])
})
