#!/usr/bin/env Rscript

library(BBmisc)

dir = file.path("pkg", "man")
fs = list.files(dir, pattern=".Rd", full.names=TRUE)
for (f in fs) {
  print(f)
  args = c("CMD", "Rd2pdf", "-o check-rds.pdf", "--force",  "--no-preview", f)
  #cmd = sprintf("R CMD Rd2pdf -o check.pdf --force  --no-preview %s > /dev/null", f)
  system3("R", args, stdout=TRUE, stderr=TRUE)
  unlink("check-rds.pdf")
}
