#!/usr/bin/env Rscript

v = system("git rev-list HEAD --count", TRUE)
revnr = max(as.integer(v))
desc = read.dcf("DESCRIPTION")
vernr = desc[, "Version"]
majorminor = strsplit(vernr, "-")[[1]][1]
vernr = sprintf("%s-%i", majorminor, revnr)
desc[,"Version"] = vernr
write.dcf(desc, file="DESCRIPTION")
cat(vernr)

