#!/usr/bin/env Rscript --vanilla

v = system("git rev-list HEAD --count", TRUE)
revision = max(as.integer(v))
desc = read.dcf("skel/DESCRIPTION")
ver = desc[,"Version"] 
ver = strsplit(ver, "-")[[1]][1]
ver = sprintf("%s-%i", ver, revision)
desc[,"Version"] = ver
write.dcf(desc, file="pkg/DESCRIPTION")
