#' @title Plot a partial dependence with plotly.
#' @description
#' Plot a partial dependence from \code{\link{generatePartialDependenceData}} using plotly.
#'
#' @family partial_dependence
#' @family plot
#'
#' @param obj [\code{PartialDependenceData}]\cr
#'   Generated by \code{\link{generatePartialDependenceData}}.
#' @param p [\code{numeric(1)}]\cr
#'   If \code{individual = TRUE} then \code{sample} allows the user to sample without replacement
#'   from the output to make the display more readable. Each row is sampled with probability \code{p}.
#'   Default is \code{1}.
#' @param show.colorbar [\code{logical(1)}]\cr
#'   Show the colorbar?
#'   Default is \code{TRUE}.
#' @param classif.alpha [\code{numeric(1)}]\cr
#'   For classification: Set transparancy of partial dependence region. Accepted value from 0 to 1.
#'   Default is 0.5.
#' @param title [\code{character(1)}]\cr
#'   Set main title for plots.
#'   Default is \code{NULL}.
#' @importFrom data.table dcast
#' @importFrom plotly plot_ly add_trace %>% layout hide_colorbar
#' @export
plotPartialDependencePlotly = function(obj, p = 1,
                                       show.colorbar = TRUE, classif.alpha = 0.5,
                                       title = NULL) {
  assertClass(obj, "PartialDependenceData")
  if (length(obj$features) %nin% c(2L, 3L) & obj$interaction)
    stop("generatePartialDependencePlotly must be called with two or three features to use this argument!")
  if (!obj$interaction)
    stop("generatePartialDependenceData was called with interaction = FALSE!")
  if (classif.alpha > 1 || classif.alpha < 0)
    warning("Valid value for classif.alpha is between 0 and 1.")

  features = obj$features

  if (p != 1) {
    assertNumber(p, lower = 0, upper = 1, finite = TRUE)
    if (!obj$individual)
      stop("generatePartialDependenceData must be called with individual = TRUE to use this argument!")
    rows = unique(obj$data$idx)
    id = sample(rows, size = floor(p * length(rows)))
    obj$data = obj$data[which(obj$data$idx %in% id), ]
  }

  if (obj$task.desc$type %in% c("regr", "classif"))
    target = obj$task.desc$target
  else
    stop("generatePartialDependencePlotly support currently only 'regression' and 'classification' tasks!")

  x1n = features[1]
  x2n = features[2]

  # Plot regression
  if (obj$task.desc$type == "regr") {
    grid.dcast = data.table::dcast(obj$data, as.formula(paste(x1n, x2n, sep = "~")), value.var = target)
    grid.3d = list(x = grid.dcast[,1],
                   y = as.numeric(colnames(grid.dcast)[-1]),
                   z = t(as.matrix(grid.dcast[,-1])))

    plt = plot_ly(x = grid.3d$x, y = grid.3d$y, z = grid.3d$z,
                  type = "surface", colorbar = list(title = target))

    plt = plt %>% layout(title = title,
                         scene = list(xaxis = list(title = paste("x: ", x1n, sep = "")),
                                      yaxis = list(title = paste("y: ", x2n, sep = "")),
                                      zaxis = list(title = paste("z: ", target, sep = ""))))
    if (!show.colorbar)
      plt = plt %>% hide_colorbar()
  }

  # Plot classification
  if (obj$task.desc$type == "classif") {
    if (length(obj$task.desc$class.levels) == 2L) {
      grid.dcast = data.table::dcast(obj$data, as.formula(paste(x1n, x2n, sep = "~")), value.var = "Probability")
      grid.3d = list(x = grid.dcast[,1],
                     y = as.numeric(colnames(grid.dcast)[-1]),
                     z = t(as.matrix(grid.dcast[,-1])))

      plt = plot_ly(x = grid.3d$x, y = grid.3d$y, z = grid.3d$z,
                    type = "surface", colorbar = list(title = target))

      plt = plt %>% layout(title = title,
                           scene = list(xaxis = list(title = paste("x: ", x1n, sep = "")),
                                        yaxis = list(title = paste("y: ", x2n, sep = "")),
                                        zaxis = list(title = "z: Probability")))
    }
    else {
      plt = plot_ly(data = obj$data, x = ~get(x1n), y = ~get(x2n), z = ~obj$data$Probability,
                    type = "mesh3d", color = ~obj$data$Class, opacity = classif.alpha)

      plt = plt %>% layout(title = title,
                           scene = list(xaxis = list(title = paste("x: ", x1n, sep = "")),
                                        yaxis = list(title = paste("y: ", x2n, sep = "")),
                                        zaxis = list(title = "z: Probability")))
    }
  }

  return(plt)
}
